# Generated by Django 5.0.7 on 2024-10-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobposition_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='description',
        ),
    ]
