# Generated by Django 5.1.1 on 2024-09-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job.skill'),
        ),
    ]
