# Generated by Django 5.1.1 on 2024-10-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant'),
        ),
    ]
