# Generated by Django 5.0.7 on 2024-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
