# Generated by Django 5.0.7 on 2024-10-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_alter_applicant_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
